### ISSUE TITLE
一些兼容性问题

### ISSUE THREAD

**Issue by zero1898** [zero1898/zero1898.github.io#1]
### CSS中的兼容性问题
  - 浏览器不支持该特性
  - 某些特定条件下触发浏览器bug

### 浏览器特性支持
  - 了解浏览器支持情况
    - [caniuse.com](http://caniuse.com/)
    - [MDN CSS Reference](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference)
    - [Codrops CSS Reference](https://tympanus.net/codrops/css_reference/)
    - [QuirksMode.org CSS](http://www.quirksmode.org/css/)

### 你需要兼容哪些浏览器
  1. 根据用户群体决定
     - 面向普通用户: IE8+、Chrome、Firefox
     - 企业级产品: IE9+、Chrome、Firefox
  2. 了解浏览器市场份额
     - 日志分析
     - 百度统计、NetMarketShare

### 浏览器不支持怎么办
  1. 如果低版本浏览器没有这个特性可以接受吗？
     - border-radius不支持时，没有圆角
     - box-shadow不支持时，没有阴影
  2. 可以使用效果稍微差一些的替代方案吗？
     - min-heihgt: 100vh, 用min-height: 800px
  3. 可以使用一些替代方案吗？
     - opacity: 0.5 在IE下用 filter:alpha(opacity=50)
  4. 可以使用javascript让浏览器支持吗？
     - 使用html5shim.js让IE6~8支持新标签
     - 使用DD_belatedPNG.js让IE6支持半透明png图片
  5. 更换实现方式

### 不同浏览器使用不同的样式
  1. @supports (现在本身兼容性就比较差，将来的方案)
     ``` css
     .container {
       display: flex;
     }
     @supports (display: grid) {
       .container {
         display: grid;
         grid-template: repeat(4, 1fr) / 50px 100px;
       }
     }
     ```
  2. 浏览器hack原理 - 层叠
     - 同一个属性，后面书写的值覆盖前面书写的值
       ``` css
       p {
         line-height: 2;
         line-height: 3;
       }
       ```
     - (对浏览器)无效的属性(值)会被忽略
       ``` css
       p {
         display: table;
         display: flex;
       }
       ```
  3. 浏览器hack原理 - 条件注释
     ``` html
     <!--[if lt IE 7 ]> <html class="ie6"> <![endif]-->
     <!--[if IE 7 ]> <html class="ie7"> <![endif]-->
     <!--[if IE 8 ]> <html class="ie8"> <![endif]-->
     <!--[if IE 9 ]> <html class="ie9"> <![endif]-->
     <!--[if (gt IE 9)|!(IE) ]><!-->
       <html class="w3c">
     <!--<![endif]-->
     ```
  4. 浏览器怪癖
     - ie6
       ``` css
       /* ie6 不支持两个类选择器直接组合*/
       .unused-class.selector {
         /* ie6 only css */
       }
       .container {
         height: 100px;
         /* 只有ie6会忽略_ */
         _height: 200px;
       }
       ```
     - ie7
       ``` css
       .container {
         height: 100px;
         /* 只有ie6和ie7会忽略* */
         *height: 200px;
       }
       ```
     - ie8
       ``` css
       /* ie6-8 不支持 :root 选择器 */
       :root .selector {
         /* ie6-8 style */
       }
       .selector {
         color: #fff;
         /* ie6-8 会忽略\9 */
         color: #fff\9;
       }
       ```

### CSS2选择器的兼容性(主要兼容性出现在ie6-7上)
  1. ie6不支持多个类直接组合
     - p.class-a.class-b被当作p.class-b
     - 解决办法: 处理好选择器优先级
  2. ie6不支持父子、兄弟选择器
     - E>F 、E+F 和 E~F 选择器无效
     - 解决方法: 避免使用，换后代选择器或其他
  3. ie6不支持属性选择器
     - 任何一种都不支持
     - 解决方法: 用class
  4. ie6-7不支持伪元素
     - 不支持 :before 和 :after
     - 解决方法: 改变实现方法，活在HTML中添加标签
  5. ie6不支持某些伪类
     - 非链接不能使用:hover 和 :active
     - 解决方法: 使用a嵌套需要hover的元素
  6. ie6-7不支持 :focus 伪类
     - 解决方法: 使用javascript
  7. ie6不支持:forst-child伪类
     - 解决方法: 给第一个子元素添加class="first"

### CSS3选择器的兼容性
  1. CSS3中的大部分选择器，兼容性是IE9+
  2. 例如 :target :empty :nth-child :nth-of-type :checked :disabled无法在IE6~8用
  3. 移动端支持绝大部分CSS3选择器

### CSS2属性的兼容性(问题主要集中在ie6上，一小部分ie7也不支持)
  1. ie6不支持min/max-width/height
     - min-height解决方法:
       ``` css
       div {
         min-height: 500px;
         _height: 500px;
       }
       ```
     - min-width解决办法
       ``` html
       <div class="container">
         <div class="strut"></div>
         <!--other content-->
       </div>
       <style>
         .container {
           min-width: 500px;
         }
         /*ie6*/
         .container .strut {
           height: 1px;
           widows: 500px;
         }
       </style>
       ```
     - max-width/height 解决办法
       - 使用javascript
  2. ie6不支持position: fixed
     ``` css
     html, body {
       height: 100%;
     }
     .go-top {
       position: fixed;
       _position: absolute;
       bottom: 0;
       right: 0;
     }
     ```
  3. ie6-7不支持块级元素inline-block
     - 行级元素支持，而块级元素不支持
     - 解决办法
       ``` css
       .selector {
         display: inline-block;
         *display: inline;
         *zoom: 1;
       }
       ```
  4. ie6-7不支持display:table
     - 请使用float或inline-block布局
     - 不要使用table布局

### CSS3属性的兼容性
  1. ie6-7不支持
  2. ie8部分支持
     - 支持
       - box-sizing
       - outline
     - 不支持
       - background-size ==> 推荐在IE8及以下使用固定宽度布局
       - border-radius
       - box-shadow
       - opacity ==> filter:alpha(opacity=50)
       - rgba, hsl, hsla
         - 一般场景下，使用相近的不透明颜色代替
         - Alpah可以通过添加额外元素，并设置透明度实现
       - rem/vh/vw/calc ==> 降级为固定宽度
  3. ie9基本都支持
     - 不支持
       - transition与animation
         - 可以接受的降级
         - 实在不能接受就用javascript
       - media query
         - 基本的媒体(all/print/screen/speech)都支持
         - 媒体特性(width/height/orientation...)IE9及以上
         - 还是建议IE8及以下使用固定宽度布局
  4. 浏览器前缀
     - 浏览器厂商为了实验新特性，在属性名前加前缀
     - Chrome/Safari/Opera: -webkit-
     - Microsoft: -ms-
     - Mozilla: -moz-

### 语义化的HTML5标签
  ``` html
  <style>
    article, main, nav, aside, section, header, footer, figure, figcaption {
      display: block;
    }
  </style>

  <!--[if lte IE 8]>
    <script src="html5shiv.js"></script>
  <![endif]-->
  ```
### 浏览器bug
  1. IE6下半透明png显示不正确
     - DD_belatedPNG.js
     - filter
       ``` css
       .selector {
         background: url(/path/to/img.png) no-repeat;
         _background: none;
         /* 图片URL必须是完整路径 */
         _filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='/path/to/img.png', sizingMethod='crop');
       }
       ```
  2. IE6浮动双边距
     - 浮动元素的与浮动同方向的边距加倍
       ``` css
       .selector {
         float: left;
         /* IE6下显示为20px */
         margin-left: 10px;
       }
       ```
     - 解决办法
       ``` css
       .selector {
         float: left;
         margin-left: 10px;
         _display: inline;
       }
       ```
  3. hasLayout
     - On Having Layout
     - zoom: 1
  4. IE模式
     - 浏览器模式Browser Mode
       - 切换渲染引擎、javascript引擎和http请求的UserAgent
       - 兼容模式相当于使用IE7的引擎
     - 文本模式
       - 切换文档模式，即渲染引擎和javascript引擎
     - 控制IE模式(<=10)
       - DocType有无控制进入怪异模式
       - meta标签控制进入哪种文档模式
         ``` html
         <!-- 使用IE7模式渲染 -->
         <mata http-equiv="X-UA-Compatible" content="IE=7">
         <!-- 使用最新引擎 -->
         <mata http-equiv="X-UA-Compatible" content="IE=edge">
         ```

### 测试兼容性
  - 虚拟机
  - [BrowserStack](https://www.browserstack.com/)

### Polyfill
  1. 使用代码帮助浏览器实现它尚未支持的特性
  2. 使用(未来)标准写法
  3. CSS Polyfill
     - [selectivizr](http://selectivizr.com/)
     - [CSS3 PIE](http://css3pie.com/)
     - [box-sizing-polyfill](https://github.com/Schepp/box-sizing-polyfill)
     - [flexibility](https://github.com/jonathantneal/flexibility)
     - [cssSandpaper](https://github.com/zoltan-dulac/cssSandpaper)
