### ISSUE TITLE
移动端适配的一些方案

### ISSUE THREAD

**Issue by zero1898** [zero1898/zero1898.github.io#2]
### 先来了解几个概念
- 物理像素(physical pixel)
  > 一个物理像素是显示器(手机屏幕)上最小的物理显示单元，在操作系统的调度下，每一个设备像素都有自己的颜色值和亮度值。

- 设备独立像素(density-independent pixel)

  > 设备独立像素(也叫密度无关像素)，可以认为是计算机坐标系统中得一个点，这个点代表一个可以由程序使用的虚拟像素(比如: css像素)，然后由相关系统转换为物理像素。

- 设备像素比(device pixel ratio)

  > 设备像素比 = 物理像素 / 设备独立像素

  > 在javascript中，可以通过window.devicePixelRatio获取到当前设备的dpr。

  > 在css中，可以通过-webkit-device-pixel-ratio，-webkit-min-device-pixel-ratio和  -webkit-max-device-pixel-ratio进行媒体查询，对不同dpr的设备，做一些样式适配(这里只针对webkit内核的浏览器和webview)。

- 视口(viewport)

  > [请点击此链接查看，文章写的很赞，长知识](http://www.cnblogs.com/2050/p/3877280.html)

### 几个适配方案

- 背景图高清化
  ``` scss
  @mixin bg-image($url) {
    background-image: url($url+"@1x.png");
    @media screen and (-webkit-min-device-pixel-ratio: 2) and (min-device-pixel-ratio: 2) {
      background-image: url($url+"@2x.png");
    }
    @media screen and (-webkit-min-device-pixel-ratio: 3) and (min-device-pixel-ratio: 3) {
      background-image: url($url+"@3x.png");
    }
  }
  ```

- border-1px
  ``` scss
  // 伪类+transform实现
  @mixin border-bottom-1px($color) {
    position: relative;
    &:after {
      display: block;
      position: absolute;
      left: 0;
      bottom: 0;
      width: 100%;
      border-bottom: 1px solid $color;
      content: ' ';
      @media screen and (-webkit-min-device-pixel-ratio: 1.5) and (min-device-pixel-ratio: 1.5) {
        -webkit-transform: scaleY(0.7);
        transform: scaleY(0.7);
      }
      @media screen and (-webkit-min-device-pixel-ratio: 2) and (min-device-pixel-ratio: 2) {
        -webkit-transform: scaleY(0.5);
        transform: scaleY(0.5);
      }
      @media screen and (-webkit-min-device-pixel-ratio: 3) and (min-device-pixel-ratio: 3) {
        -webkit-transform: scaleY(0.33333);
        transform: scaleY(0.33333);
      }
    }
  }
  ```

- 手淘Flexible方案
  > [请点击此链接查看详情](https://github.com/amfe/article/issues/17)

  ``` scss
  // 去除一个值的单位
  @function strip-units($number) {
    @return $number / ($number * 0 + 1);
  }
  // px转rem function
  @function px2rem($px-value) {
    $px-value: strip-units($px-value);
    $base-font-size: strip-units($base-font-size);
    @if ($px-value==0) {
      @return $px-value;
    }
    @return #{$px-value / $base-font-size}rem;
  }
  // px转rem mixin
  @mixin px2rem($property, $px-values) {
    $base-font-size: strip-units($base-font-size);
    $pxs: "";
    $rems: "";
    @each $px-value in $px-values {
      @if $px-value==0 or type-of($px-value) !="number" {
        $pxs: #{$pxs + " " + $px-value};
        $rems: #{$rems + " " + $px-value};
      }
      @else {
        $px-value: strip-units($px-value);
        $pxs: #{$pxs + " " + $px-value}px;
        $rems: #{$rems + " " + $px-value / $base-font-size}rem;
      }
    }
    @if $rem-not-support-for-ie {
      #{$property}: $pxs;
    }
    #{$property}: $rems;
  }
  ```

  ``` scss
  // 自动适配字体的sass mixin
  @mixin font-dpr($font-size){
      font-size: $font-size;

      [data-dpr="2"] & {
          font-size: $font-size * 2;
      }

      [data-dpr="3"] & {
          font-size: $font-size * 3;
      }
  }
  ```
